
services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    container_name: sync-user
    ports:
      - "7002:8000"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/
      - ./ml/model/:/app/ml/model/
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
    
